var data = [{'startTime': '2022-01-10 21:01:52', 'duration': '0:01:10.504090', 'title': '口语App自动化测试报告', 'status': '错误 2', 'desc': '用例执行情况', 'data': '\n    <div id="btn-group">\n    <div class="btn-group btn-group-sm">\n        <a class="btn btn-primary" onclick=\'javascript:showCase(0)\'>概要{ 0.00% }</a>\n        <a class="btn btn-warning" onclick=\'javascript:showCase(4)\'>错误{ 2 }</a>\n        <a class="btn btn-danger" onclick=\'javascript:showCase(1)\'>失败{ 0 }</a>\n        <a class="btn btn-success" onclick=\'javascript:showCase(2)\'>通过{ 0 }</a>\n        <a class="btn btn-info" onclick=\'javascript:showCase(3)\'>所有{ 2 }</a>\n    </div>\n    <p></p>\n    <table id=\'result_table\' class="table table-bordered">\n        <colgroup>\n            <col align=\'left\' />\n            <col align=\'right\' />\n            <col align=\'right\' />\n            <col align=\'right\' />\n            <col align=\'right\' />\n            <col align=\'right\' />\n            <col align=\'right\' />\n        </colgroup>\n        <tr id=\'header_row\'>\n            <td>测试套件/测试用例</td>\n            <td>总数</td>\n            <td>通过</td>\n            <td>失败</td>\n            <td>错误</td>\n            <th>视图</th>\n            <th>错误截图</th>\n        </tr>\n        \n    <tr class=\'errorClass\'>\n        <td>unittest.suite._ErrorHolder</td>\n        <td>2</td>\n        <td>0</td>\n        <td>0</td>\n        <td>2</td>\n        <td><a href="javascript:showClassDetail(\'c1\',2)">详情</a></td>\n        <td>&nbsp;</td>\n    </tr>\n\n<tr id=\'ft1.1\' class=\'none\'>\n    <td class=\'errorCase\'><div class=\'testcase\'>CaseLogin)</div></td>\n    <td colspan=\'5\' align=\'center\'>\n    <!--css div popup start-->\n    <a class="popup_link" onfocus=\'this.blur();\' href="javascript:showTestDetail(\'div_ft1.1\')" >\n        错误</a>\n    <div id=\'div_ft1.1\' class="popup_window">\n        <div style=\'text-align: right; color:red;cursor:pointer\'>\n            <a onfocus=\'this.blur();\' onclick="document.getElementById(\'div_ft1.1\').style.display = \'none\' " >\n               [x]</a>\n        </div>\n        <pre>ft1.1: Traceback (most recent call last):\n  File "C:\\Users\\yading2\\Downloads\\AppiumPython-master\\Page\\BasePage.py", line 35, in setUpClass\n    cls.driver = webdriver.Remote(\'http://localhost:4723/wd/hub\', desired_caps)\n  File "D:\\Python37\\lib\\site-packages\\appium\\webdriver\\webdriver.py", line 274, in __init__\n    AppiumConnection(command_executor, keep_alive=keep_alive), desired_capabilities, browser_profile, proxy\n  File "D:\\Python37\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py", line 268, in __init__\n    self.start_session(capabilities, browser_profile)\n  File "D:\\Python37\\lib\\site-packages\\appium\\webdriver\\webdriver.py", line 364, in start_session\n    response = self.execute(RemoteCommand.NEW_SESSION, parameters)\n  File "D:\\Python37\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py", line 424, in execute\n    self.error_handler.check_response(response)\n  File "D:\\Python37\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py", line 247, in check_response\n    raise exception_class(message, screen, stacktrace)\nselenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not find a connected Android device.\nStacktrace:\nUnknownError: An unknown server-side error occurred while processing the command. Original error: Could not find a connected Android device.\n    at getResponseForW3CError (C:\\Users\\yading2\\AppData\\Local\\Programs\\Appium\\resources\\app\\node_modules\\appium\\node_modules\\appium-base-driver\\lib\\protocol\\errors.js:826:9)\n    at asyncHandler$ (C:\\Users\\yading2\\AppData\\Local\\Programs\\Appium\\resources\\app\\node_modules\\appium\\node_modules\\appium-base-driver\\lib\\protocol\\protocol.js:404:37)\n    at tryCatch (C:\\Users\\yading2\\AppData\\Local\\Programs\\Appium\\resources\\app\\node_modules\\appium\\node_modules\\babel-runtime\\regenerator\\runtime.js:67:40)\n    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\\Users\\yading2\\AppData\\Local\\Programs\\Appium\\resources\\app\\node_modules\\appium\\node_modules\\babel-runtime\\regenerator\\runtime.js:315:22)\n    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\\Users\\yading2\\AppData\\Local\\Programs\\Appium\\resources\\app\\node_modules\\appium\\node_modules\\babel-runtime\\regenerator\\runtime.js:100:21)\n    at GeneratorFunctionPrototype.invoke (C:\\Users\\yading2\\AppData\\Local\\Programs\\Appium\\resources\\app\\node_modules\\appium\\node_modules\\babel-runtime\\regenerator\\runtime.js:136:37)\n    at &lt;anonymous&gt;\n</pre>\n    </div>\n    <!--css div popup end-->\n    </td>\n    <td>无截图</td>\n</tr>\n\n<tr id=\'ft1.2\' class=\'none\'>\n    <td class=\'errorCase\'><div class=\'testcase\'>CaseAnsq)</div></td>\n    <td colspan=\'5\' align=\'center\'>\n    <!--css div popup start-->\n    <a class="popup_link" onfocus=\'this.blur();\' href="javascript:showTestDetail(\'div_ft1.2\')" >\n        错误</a>\n    <div id=\'div_ft1.2\' class="popup_window">\n        <div style=\'text-align: right; color:red;cursor:pointer\'>\n            <a onfocus=\'this.blur();\' onclick="document.getElementById(\'div_ft1.2\').style.display = \'none\' " >\n               [x]</a>\n        </div>\n        <pre>ft1.2: Traceback (most recent call last):\n  File "C:\\Users\\yading2\\Downloads\\AppiumPython-master\\Page\\BasePage.py", line 35, in setUpClass\n    cls.driver = webdriver.Remote(\'http://localhost:4723/wd/hub\', desired_caps)\n  File "D:\\Python37\\lib\\site-packages\\appium\\webdriver\\webdriver.py", line 274, in __init__\n    AppiumConnection(command_executor, keep_alive=keep_alive), desired_capabilities, browser_profile, proxy\n  File "D:\\Python37\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py", line 268, in __init__\n    self.start_session(capabilities, browser_profile)\n  File "D:\\Python37\\lib\\site-packages\\appium\\webdriver\\webdriver.py", line 364, in start_session\n    response = self.execute(RemoteCommand.NEW_SESSION, parameters)\n  File "D:\\Python37\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py", line 424, in execute\n    self.error_handler.check_response(response)\n  File "D:\\Python37\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py", line 247, in check_response\n    raise exception_class(message, screen, stacktrace)\nselenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not find a connected Android device.\nStacktrace:\nUnknownError: An unknown server-side error occurred while processing the command. Original error: Could not find a connected Android device.\n    at getResponseForW3CError (C:\\Users\\yading2\\AppData\\Local\\Programs\\Appium\\resources\\app\\node_modules\\appium\\node_modules\\appium-base-driver\\lib\\protocol\\errors.js:826:9)\n    at asyncHandler$ (C:\\Users\\yading2\\AppData\\Local\\Programs\\Appium\\resources\\app\\node_modules\\appium\\node_modules\\appium-base-driver\\lib\\protocol\\protocol.js:404:37)\n    at tryCatch (C:\\Users\\yading2\\AppData\\Local\\Programs\\Appium\\resources\\app\\node_modules\\appium\\node_modules\\babel-runtime\\regenerator\\runtime.js:67:40)\n    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\\Users\\yading2\\AppData\\Local\\Programs\\Appium\\resources\\app\\node_modules\\appium\\node_modules\\babel-runtime\\regenerator\\runtime.js:315:22)\n    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\\Users\\yading2\\AppData\\Local\\Programs\\Appium\\resources\\app\\node_modules\\appium\\node_modules\\babel-runtime\\regenerator\\runtime.js:100:21)\n    at GeneratorFunctionPrototype.invoke (C:\\Users\\yading2\\AppData\\Local\\Programs\\Appium\\resources\\app\\node_modules\\appium\\node_modules\\babel-runtime\\regenerator\\runtime.js:136:37)\n    at &lt;anonymous&gt;\n</pre>\n    </div>\n    <!--css div popup end-->\n    </td>\n    <td>无截图</td>\n</tr>\n\n        <tr id=\'total_row\'>\n            <td>总计</td>\n            <td>2</td>\n            <td>0</td>\n            <td>0</td>\n            <td>2</td>\n            <td>&nbsp;</td>\n            <th>&nbsp;</th>\n        </tr>\n    </table>\n    </div>\n', 'error': '2'}]